language: node_js
node_js: '10'

env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    
matrix:
  include:
    - os: osx
      osx_image: xcode10.2

    - os: linux

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - yarn electron:build

branches:
  except:
    - 'dev'
